
/-
Who knows how much of this we need.

Lemma 10.16.2. Let R be a ring.

    The spectrum of a ring R is empty if and only if R is the zero ring.
    Every nonzero ring has a maximal ideal.
    Every nonzero ring has a minimal prime ideal.
    Given an ideal I⊂R and a prime ideal I⊂𝔭 there exists a prime I⊂𝔮⊂𝔭 such that 𝔮 is minimal over I.
    If T⊂R, and if (T) is the ideal generated by T in R, then V((T))=V(T).
    If I is an ideal and I√ is its radical, see basic notion (27), then V(I)=V(I√).
    Given an ideal I of R we have I√=⋂I⊂𝔭𝔭.
    If I is an ideal then V(I)=∅ if and only if I is the unit ideal.
    If I, J are ideals of R then V(I)∪V(J)=V(I∩J).
    If (Ia)a∈A is a set of ideals of R then ∩a∈AV(Ia)=V(∪a∈AIa).
    If f∈R, then D(f)⨿V(f)=Spec(R).
    If f∈R then D(f)=∅ if and only if f is nilpotent.
    If f=uf′ for some unit u∈R, then D(f)=D(f′).
    If I⊂R is an ideal, and 𝔭 is a prime of R with 𝔭∉V(I), then there exists an f∈R such that 𝔭∈D(f), and D(f)∩V(I)=∅.
    If f,g∈R, then D(fg)=D(f)∩D(g).
    If fi∈R for i∈I, then ⋃i∈ID(fi) is the complement of V({fi}i∈I) in Spec(R).
    If f∈R and D(f)=Spec(R), then f is a unit. 

Proof. We address each part in the corresponding item below.

    This is a direct consequence of (2) or (3).
    Let 𝔄 be the set of all proper ideals of R. This set is ordered by inclusion and is non-empty, since (0)∈𝔄 is a proper ideal. Let A be a totally ordered subset of 𝔄. Then ⋃I∈AI is in fact an ideal. Since 1 ∉I for all I∈A, the union does not contain 1 and thus is proper. Hence ⋃I∈AI is in 𝔄 and is an upper bound for the set A. Thus by Zorn's lemma 𝔄 has a maximal element, which is the sought-after maximal ideal.
    Since R is nonzero, it contains a maximal ideal which is a prime ideal. Thus the set 𝔄 of all prime ideals of R is nonempty. 𝔄 is ordered by reverse-inclusion. Let A be a totally ordered subset of 𝔄. It's pretty clear that J=⋂I∈AI is in fact an ideal. Not so clear, however, is that it is prime. Let xy∈J. Then xy∈I for all I∈A. Now let B={I∈A|y∈I}. Let K=⋂I∈BI. Since A is totally ordered, either K=J (and we're done, since then y∈J) or K⊃J and for all I∈A such that I is properly contained in K, we have y∉I. But that means that for all those I,x∈I, since they are prime. Hence x∈J. In either case, J is prime as desired. Hence by Zorn's lemma we get a maximal element which in this case is a minimal prime ideal.
    This is the same exact argument as (3) except you only consider prime ideals contained in 𝔭 and containing I.
    (T) is the smallest ideal containing T. Hence if T⊂I, some ideal, then (T)⊂I as well. Hence if I∈V(T), then I∈V((T)) as well. The other inclusion is obvious.
    Since I⊂I√,V(I√)⊂V(I). Now let 𝔭∈V(I). Let x∈I√. Then xn∈I for some n. Hence xn∈𝔭. But since 𝔭 is prime, a boring induction argument gets you that x∈𝔭. Hence I√⊂𝔭 and 𝔭∈V(I√).
    Let f∈R∖I√. Then fn∉I for all n. Hence S={1,f,f2,…} is a multiplicative subset, not containing 0. Take a prime ideal 𝔭¯⊂S−1R containing S−1I. Then the pull-back 𝔭 in R of 𝔭¯ is a prime ideal containing I that does not intersect S. This shows that ⋂I⊂𝔭𝔭⊂I√. Now if a∈I√, then an∈I for some n. Hence if I⊂𝔭, then an∈𝔭. But since 𝔭 is prime, we have a∈𝔭. Thus the equality is shown.
    I is not the unit ideal if and only if I is contained in some maximal ideal (to see this, apply (2) to the ring R/I) which is therefore prime.
    If 𝔭∈V(I)∪V(J), then I⊂𝔭 or J⊂𝔭 which means that I∩J⊂𝔭. Now if I∩J⊂𝔭, then IJ⊂𝔭 and hence either I of J is in 𝔭, since 𝔭 is prime.
    𝔭∈⋂a∈AV(Ia)⇔Ia⊂𝔭,∀a∈A⇔𝔭∈V(∪a∈AIa)
    If 𝔭 is a prime ideal and f∈R, then either f∈𝔭 or f∉𝔭 (strictly) which is what the disjoint union says.
    If a∈R is nilpotent, then an=0 for some n. Hence an∈𝔭 for any prime ideal. Thus a∈𝔭 as can be shown by induction and D(f)=∅. Now, as shown in (7), if a∈R is not nilpotent, then there is a prime ideal that does not contain it.
    f∈𝔭⇔uf∈𝔭, since u is invertible.
    If 𝔭∉V(I), then ∃f∈I∖𝔭. Then f∉𝔭 so 𝔭∈D(f). Also if 𝔮∈D(f), then f∉𝔮 and thus I is not contained in 𝔮. Thus D(f)∩V(I)=∅.
    If fg∈𝔭, then f∈𝔭 or g∈𝔭. Hence if f∉𝔭 and g∉𝔭, then fg∉𝔭. Since 𝔭 is an ideal, if fg∉𝔭, then f∉𝔭 and g∉𝔭.
    𝔭∈⋃i∈ID(fi)⇔∃i∈I,fi∉𝔭⇔𝔭∈Spec(R)∖V({fi}i∈I)
    If D(f)=Spec(R), then V(f)=∅ and hence fR=R, so f is a unit. 


\begin{lemma}
\label{lemma-Zariski-topology}
Let $R$ be a ring.
\begin{enumerate}
\item The spectrum of a ring $R$ is empty if and only if $R$
is the zero ring.
\item Every nonzero ring has a maximal ideal.
\item Every nonzero ring has a minimal prime ideal.
\item Given an ideal $I \subset R$ and a prime ideal
$I \subset \mathfrak p$ there exists a prime
$I \subset \mathfrak q \subset \mathfrak p$ such
that $\mathfrak q$ is minimal over $I$.
\item If $T \subset R$, and if $(T)$ is the ideal generated by
$T$ in $R$, then $V((T)) = V(T)$.
\item If $I$ is an ideal and $\sqrt{I}$ is its radical,
see basic notion (\ref{item-radical-ideal}), then $V(I) = V(\sqrt{I})$.
\item Given an ideal $I$ of $R$ we have $\sqrt{I} =
\bigcap_{I \subset \mathfrak p} \mathfrak p$.
\item If $I$ is an ideal then $V(I) = \emptyset$ if and only
if $I$ is the unit ideal.
\item If $I$, $J$ are ideals of $R$ then $V(I) \cup V(J) =
V(I \cap J)$.
\item If $(I_a)_{a\in A}$ is a set of ideals of $R$ then
$\cap_{a\in A} V(I_a) = V(\cup_{a\in A} I_a)$.
\item If $f \in R$, then $D(f) \amalg V(f) = \Spec(R)$.
\item If $f \in R$ then $D(f) = \emptyset$ if and only if $f$
is nilpotent.
\item If $f = u f'$ for some unit $u \in R$, then $D(f) = D(f')$.
\item If $I \subset R$ is an ideal, and $\mathfrak p$ is a prime of
$R$ with $\mathfrak p \not\in V(I)$, then there exists an $f \in R$
such that $\mathfrak p \in D(f)$, and $D(f) \cap V(I) = \emptyset$.
\item If $f, g \in R$, then $D(fg) = D(f) \cap D(g)$.
\item If $f_i \in R$ for $i \in I$, then
$\bigcup_{i\in I} D(f_i)$ is the complement of $V(\{f_i \}_{i\in I})$
in $\Spec(R)$.
\item If $f \in R$ and $D(f) = \Spec(R)$, then $f$ is a unit.
\end{enumerate}
\end{lemma}

\begin{proof}
We address each part in the corresponding item below.
\begin{enumerate}
\item This is a direct consequence of (2) or (3).
\item Let $\mathfrak{A}$ be the set of all proper ideals of $R$. This set is
ordered by inclusion and is non-empty, since $(0) \in \mathfrak{A}$ is a proper
ideal. Let $A$ be a totally ordered subset of $\mathfrak A$.
Then $\bigcup_{I \in A} I$ is in
fact an ideal. Since 1 $\notin I$ for all $I \in A$, the union does not contain
1 and thus is proper. Hence $\bigcup_{I \in A} I$ is in $\mathfrak{A}$ and is
an upper bound for the set $A$. Thus by Zorn's lemma $\mathfrak{A}$ has a
maximal element, which is the sought-after maximal ideal.
\item Since $R$ is nonzero, it contains a maximal ideal which is a prime ideal.
Thus the set $\mathfrak{A}$ of all prime ideals of $R$ is nonempty.
$\mathfrak{A}$ is ordered by reverse-inclusion. Let $A$ be a totally ordered
subset of $\mathfrak{A}$. It's pretty clear that $J = \bigcap_{I \in A} I$ is
in fact an ideal. Not so clear, however, is that it is prime. Let $xy \in J$.
Then $xy \in I$ for all $I \in A$. Now let $B = \{I \in A | y \in I\}$. Let $K
= \bigcap_{I \in B} I$. Since $A$ is totally ordered, either $K = J$ (and we're
done, since then $y \in J$) or $K \supset J$ and for all $I \in A$ such that
$I$ is properly contained in $K$, we have $y \notin I$. But that means that for
all those $I, x \in I$, since they are prime. Hence $x \in J$. In either case,
$J$ is prime as desired. Hence by Zorn's lemma we get a maximal element which
in this case is a minimal prime ideal.
\item This is the same exact argument as (3) except you only consider prime
ideals contained in $\mathfrak{p}$ and containing $I$.
\item $(T)$ is the smallest ideal containing $T$. Hence if $T \subset I$, some
ideal, then $(T) \subset I$ as well. Hence if $I \in V(T)$, then $I \in V((T))$
as well. The other inclusion is obvious.
\item Since $I \subset \sqrt{I}, V(\sqrt{I}) \subset V(I)$. Now let
$\mathfrak{p} \in V(I)$. Let $x \in \sqrt{I}$. Then $x^n \in I$ for some $n$.
Hence $x^n \in \mathfrak{p}$. But since $\mathfrak{p}$ is prime, a boring
induction argument gets you that $x \in \mathfrak{p}$. Hence $\sqrt{I} \subset
\mathfrak{p}$ and $\mathfrak{p} \in V(\sqrt{I})$.
\item Let $f \in R \setminus \sqrt{I}$. Then $f^n \notin I$ for all $n$. Hence
$S = \{1, f, f^2, \ldots\}$ is a multiplicative subset, not containing $0$.
Take a
prime ideal $\bar{\mathfrak{p}} \subset S^{-1}R$ containing $S^{-1}I$. Then the
pull-back $\mathfrak{p}$ in $R$ of $\bar{\mathfrak{p}}$ is a prime ideal
containing $I$ that does not intersect $S$. This shows that $\bigcap_{I \subset
\mathfrak p} \mathfrak p \subset \sqrt{I}$. Now if $a \in \sqrt{I}$, then $a^n
\in I$ for some $n$. Hence if $I \subset \mathfrak{p}$, then $a^n \in
\mathfrak{p}$. But since $\mathfrak{p}$ is prime, we have $a \in \mathfrak{p}$.
Thus the equality is shown.
\item $I$ is not the unit ideal if and only if $I$
is contained in some maximal ideal (to
see this, apply (2) to the ring $R/I$) which is therefore prime.
\item If $\mathfrak{p} \in V(I) \cup V(J)$, then $I \subset \mathfrak{p}$ or $J
\subset \mathfrak{p}$ which means that $I \cap J \subset \mathfrak{p}$. Now if
$I \cap J \subset \mathfrak{p}$, then $IJ \subset \mathfrak{p}$ and hence
either $I$ of $J$ is in $\mathfrak{p}$, since $\mathfrak{p}$ is prime.
\item $\mathfrak{p} \in \bigcap_{a \in A} V(I_a) \Leftrightarrow I_a \subset
\mathfrak{p}, \forall a \in A \Leftrightarrow \mathfrak{p} \in V(\cup_{a\in A}
I_a)$
\item If $\mathfrak{p}$ is a prime ideal and $f \in R$, then either $f \in
\mathfrak{p}$ or $f \notin \mathfrak{p}$ (strictly) which is what the disjoint
union says.
\item If $a \in R$ is nilpotent, then $a^n = 0$ for some $n$. Hence $a^n \in
\mathfrak{p}$ for any prime ideal. Thus $a \in \mathfrak{p}$ as can be shown by
induction and $D(f) = \emptyset$. Now, as shown in (7), if $a \in R$ is not
nilpotent, then there is a prime ideal that does not contain it.
\item $f \in \mathfrak{p} \Leftrightarrow uf \in \mathfrak{p}$, since $u$ is
invertible.
\item If $\mathfrak{p} \notin V(I)$, then $\exists f \in I \setminus
\mathfrak{p}$. Then $f \notin \mathfrak{p}$ so $\mathfrak{p} \in D(f)$. Also if
$\mathfrak{q} \in D(f)$, then $f \notin \mathfrak{q}$ and thus $I$ is not
contained in $\mathfrak{q}$. Thus $D(f) \cap V(I) = \emptyset$.
\item If $fg \in \mathfrak{p}$, then $f \in \mathfrak{p}$ or $g \in
\mathfrak{p}$. Hence if $f \notin \mathfrak{p}$ and $g \notin \mathfrak{p}$,
then $fg \notin \mathfrak{p}$. Since $\mathfrak{p}$ is an ideal, if $fg \notin
\mathfrak{p}$, then $f \notin \mathfrak{p}$ and $g \notin \mathfrak{p}$.
\item $\mathfrak{p} \in \bigcup_{i \in I} D(f_i) \Leftrightarrow \exists i \in
I, f_i \notin \mathfrak{p} \Leftrightarrow \mathfrak{p} \in \Spec(R)
\setminus V(\{f_i\}_{i \in I})$
\item If $D(f) = \Spec(R)$, then $V(f) = \emptyset$ and
hence $fR = R$, so $f$ is a unit.
\end{enumerate}
\end{proof}
-/
