/-
Lemma 10.16.10. Let R be a ring. The space Spec(R) is quasi-compact.

Proof. It suffices to prove that any covering of Spec(R) by standard opens can be refined by a finite covering. Thus suppose that Spec(R)=∪D(fi) for a set of elements {fi}i∈I of R. This means that ∩V(fi)=∅. According to Lemma 10.16.2 (00E0) this means that V({fi})=∅. According to the same lemma this means that the ideal generated by the fi is the unit ideal of R. This means that we can write 1 as a finite sum: 1=∑i∈Jrifi with J⊂I finite. And then it follows that Spec(R)=∪i∈JD(fi). 
-/

import Kenny_comm_alg.Zariski
universes u v
lemma lemma_quasi_compact {R : Type u} [comm_ring R] : compact (@set.univ (X R)) := sorry